security:
    role_hierarchy:
        ROLE_ADMIN: ROLE_USER

    # Hashing de contraseÃ±as
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    # Cargar usuarios desde la BD
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: app_user_provider
            custom_authenticator: App\Security\LoginFormAuthenticator

            logout:
                path: app_logout
                # ðŸ”¥ RedirecciÃ³n despuÃ©s de cerrar sesiÃ³n
                target: app_home

            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800  # 1 semana
                path: /
                always_remember_me: true

    # PROTECCIÃ“N DE RUTAS
    access_control:

        # Rutas solo para usuarios logueados
        - { path: ^/home, roles: ROLE_USER }
        - { path: ^/perfil, roles: ROLE_USER }
        - { path: ^/profile, roles: ROLE_USER }
        - { path: ^/products, roles: ROLE_USER }
        - { path: ^/recomendaciones, roles: ROLE_USER }
        - { path: ^/stores, roles: ROLE_USER }

        # CRUD categorÃ­as â€“ ADMIN
        - { path: ^/category/new, roles: ROLE_ADMIN }
        - { path: ^/category/\d+/edit, roles: ROLE_ADMIN }
        - { path: ^/category/\d+, roles: ROLE_ADMIN }

        # CRUD productos â€“ ADMIN
        - { path: ^/product/new, roles: ROLE_ADMIN }
        - { path: ^/product/\d+/edit, roles: ROLE_ADMIN }
        - { path: ^/product/\d+, roles: ROLE_ADMIN }
        - { path: ^/product, roles: ROLE_ADMIN }

        # Panel admin
        - { path: ^/admin, roles: ROLE_ADMIN }


when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10
